### ISSUE TITLE
Inactive Development

### ISSUE THREAD

**Issue by pacollins** [jpescador/hugo-future-imperfect#47]
@jpescador I noticed that this was inactive and was trying to find a way to contact you (but no listed email) to ask if you mind if I, or someone else, take over its development - including change where gohugo.io references. I think the theme is great and I would love for people to be able to keep using it and keep it up to date. Let me know either here or on the issue posted on gohugoio/hugoThemes#285.

**Comment by jpescador** [comment]
@pacollins, I don't know where to begin. It brings me much joy that there are so many people interested in this theme and unfortunately I did not give the theme much TLC after its release. Fortunately there were many just like you people who kept this repo alive! I will start taking a look at the tickets....although at this point I may consider one master PR since I noticed you're ahead by 49 commits! Nevertheless, let me set up my local environment and we can go from there. Thank you again to everyone and in no specific order: @pacollins @norcalbiostat @klud1 @castaways @vikas-0 @ex-nerd @ianmcxa @bubuzzz @glnarayanan @seepa @tattwamasi @justrjlewis @qwding @zeebluejay @onrea @stefanwalther @Sankame @yaningo @bwinterton @Jean85 @taueres @joshkestenberg @kaystrobach @7sharp9 @perpi

**Comment by pacollins** [comment]
@jpescador Just checking in on this.

**Comment by jpescador** [comment]
Hey @pacollins, I'll use your PR, #48. I'll have this merged before the end of the week. Thanks for putting together this master PR!

**Comment by pacollins** [comment]
No problem! I know you are probably busy, I just want to keep the ball rolling so the theme can be included back to the official Hugo site.

**Comment by jpescador** [comment]
#48 has been merged, thanks again!
