### ISSUE TITLE
Long lines in post content breaks the layout 

### ISSUE THREAD

**Issue by Jean85** [jpescador/hugo-future-imperfect#8]
I'm having an issue with large items inside the content. 
If I add something too large, the sidebar gets pushed to the side, without the possibility of scrolling the browser horizontally. 

With images, this could be easily fixed with a `img {max-width: 100%}` CSS rule. But that is feasible because images are wrapped inside a `p` element. 

The same issue is present (and not resolved in my case) with large block of code. The `pre` and `code` elements doesn't respond to the same rule, so I don't know how to fix it! 

Anyone knows how to resolve this?

**Comment by jpescador** [comment]
Hi Alessandro, I noticed this as well with large blocks of code (https://github.com/jpescador/hugo-future-imperfect/commit/30f4dd03449030ba3cfc36d16c87196d6d815fe6). I tried to wrap the text, but the output just didn't look appealing. The workaround for the moment is to limit the number of characters to 80 per line for the moment until a fix can be found.

As for the images, have you tried using the shortcodes img-post or img-fit? You have the option to place the image to the left, center, or to the right like so for img-post:

```
{{< img-post "/path/to/file" "filename" "alt text" "left" >}}
```
As for img-fit you can use this for one image rather than multiple. For example, if you want the image to fill the width of the content area you can do something like this:

```
{{< img-fit "12u$" "filename" "alt text" "/path/to/file" >}}
```

Please note that you also have two alternate options as well rather than just setting an explicit path for the mentioned shortcodes.
You can use date or title which will use the following paths:

```
title: will use /img/LinkTitle as the path
date: will use /img/year/month as the path
```

**Comment by Jean85** [comment]
Thanks for your suggestions. Img solutions are all very good, but for large blocks of code this is not feasible for me. In (one of) my cases, I want to display a block of encoded data and present it as it is, so breaking it at the 80th character it's against it.

I will dig further in Hugo docs to see if we can do something in the default partials.

**Comment by Jean85** [comment]
I haven't found any fixes for now :cry: I've resorted to a fixed max-width of 50em, that is near to the maximum width achievable in the widest format. On lower resolutions, the container width takes the precedence and all works well already.

**Comment by jpescador** [comment]
Hi @Jean85, a fix has been applied for the large lines of code issue. I also took a look at your website and noticed some personal customizations. If you would like to contribute to the theme, feel free to create a PR :wink:

**Comment by Jean85** [comment]
Yeah, thanks for the fix! ;) I'll back port it to our blog!

Our blog has some personalizations indeed, but most of it are personal preferences (like the filtering on the top categories bumped to more elements, or the non-uppercase titles).
The only major change is the multi-author support through taxonomies, but I'm having some template issue in the top-right box in the article which shows the author, 'cause I've added the author's avatar; the same issue is also adding in on top of an other edit that I did, a sub-link under the article's title to a translated version of it. It adds some height to the header, unbalancing the right box too.
