### ISSUE TITLE
Error on running Hugo

### ISSUE THREAD

**Issue by 7sharp9** [jpescador/hugo-future-imperfect#9]
Hi nice theme, I get the following error on running with this theme in the console output:

>ERROR: 2016/04/23 reflect: call of reflect.Value.Type on zero Value in theme/post/footer-category.html

**Comment by daoran** [comment]
The error is possibly because your content folder (in your base Hugo folder) has something other than blog and about.md. It seems to me that you have a post folder inside the content folder. Please see the exampleSite folder, your content folder can only have blog and about.md.

**Comment by 7sharp9** [comment]
Yeah your right, although I do have some markdown consistencies between hugo and hexo, where hexo did not require a `---` initial front matter which resulted in no posts being show.  Somehow they are all displayed if I used a different folder than the theme.

I had a folder named post with all my `*.md`'s I then modified the menu sections to point to the new location and all my posts were show, that was when I noticed the errors in the log.

Anyway, Ill follow the correct instructions and fix the front matter, thanks!

**Comment by jpescador** [comment]
Hi Dave, thanks! As for the error, I was able to reproduce it and it turns out the reason you got this error was because the **categories** variable was not set in the front matter. I'm guessing you may have manually created the Hugo section directory as well as the content markdown files. If you run the `hugo new` command then the archetype will be used to set the default configuration properties. For example, if you run:
```
hugo new blog/my-first-post.md
```

The blog archetype from the theme will be used and set the default variables in the front matter.

If you run this command then the default archetype will be used. 
```
hugo new post/my-first-post.md
```

I'll be updating the footer-category html file so that the error no longer happens. Thank you for reporting it.
